language: node_js

cache:
  yarn: true
  directories:
    - node_modules

node_js:
- '6.11.3'

install:
- yarn install
- yarn build

deploy:
- provider: npm
  email: saching@microsoft.com
  skip_cleanup: true
  api_key: $NPM_DEPLOY_TOKEN
  on:
    branch: master