# This pipeline checks-out current client sdk repo and stable app hosting sdk repo (as specified in AppHostingSdkGitRef).
# It then runs a script which is responsible for locally running Teams Test App and Orange host.
# And then running E2E tests and publishing them.

trigger:
  - '2.0-preview'
  - 'release*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
  - checkout: git://$(AppHostingSdkGitPath)@$(AppHostingSdkGitRef)
    persistCredentials: true

  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - task: YarnInstaller@3
    inputs:
      versionSpec: '1.x'

  - task: Yarn@2
    displayName: 'Run yarn on app hosting sdk'
    inputs:
      Arguments:
      ProjectDirectory: '$(AppHostingSdkProjectDirectory)'

  - task: Yarn@2
    displayName: 'Build app hosting sdk'
    inputs:
      Arguments: 'build'
      ProjectDirectory: '$(AppHostingSdkProjectDirectory)'

  - task: Yarn@2
    displayName: 'Run yarn on client sdk'
    inputs:
      Arguments:
      ProjectDirectory: '$(ClientSdkProjectDirectory)'

  - task: Yarn@2
    displayName: 'Build client sdk'
    inputs:
      Arguments: 'build'
      ProjectDirectory: '$(ClientSdkProjectDirectory)'

  - task: Yarn@2
    displayName: 'Build Test App Local'
    inputs:
      Arguments: 'build-test-app-local'
      ProjectDirectory: '$(ClientSdkProjectDirectory)'

  - task: CmdLine@2
    displayName: 'Configure host machine'
    inputs:
      script: |
        sudo chmod -R 755 ./ 
        sudo yarn setup
      workingDirectory: '$(AppHostingSdkProjectDirectory)'

  - bash: 'node tools/cli/runAppsWithE2ETests.js --envType=localScriptTag'
    displayName: 'Run E2E integration tests'
    condition: succeeded()
    workingDirectory: '$(AppHostingSdkProjectDirectory)'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/e2e-tests-report*.xml'
    condition: succeededOrFailed()

  - task: ComponentGovernanceComponentDetection@0
    inputs:
      scanType: 'LogOnly'
      verbosity: 'Verbose'
      alertWarningLevel: 'High'
      failOnAlert: true
