# This template handles running E2E tests (including all necessary setup steps) from the host SDK repo for various environments.
# It will run one E2E job for each testPrefixPattern selector in the testPrefixPatternGroups parameter.

parameters:
  - name: AppHostingSdk
    default: none
    type: string

jobs:
  - job: E2ETest1
    displayName: 'E2E Test - Perf'
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: 'ubuntu-latest'
      os: linux
    steps:
      - template: tools/yaml-templates/build-app-host.yml@self
        parameters:
          appHostGitPath: AppHostingSdk
