# This template handles running E2E tests (including all necessary setup steps) from the host SDK repo for various environments.
# It will run one E2E job for each testPrefixPattern selector in the testPrefixPatternGroups parameter.

parameters:
  - name: AppHostingSdk
    default: none
    type: string
  - name: hostingEnvironmentType
    type: string
    values:
      - 'standardWeb'
  - name: teamsJsReferenceType
    type: string
    values:
      - 'npm'
      - 'scriptTag'
  - name: testPrefixPatternGroups
    type: object
    default: ['{[A-Z],[a-z],[0-9]}']
  - name: versionBranch
    type: string
    default: none

jobs:
  - ${{each testPrefixPattern in parameters.testPrefixPatternGroups}}:
      # This replaces all characters expected to be see in the test prefix pattern that are not valid in a job name with underscores.
      # Sadly ADO does not support regex matching here at this time.
      - job: E2ETestsWeb_${{ parameters.versionBranch }}_${{ parameters.teamsJsReferenceType }}_${{ replace(
          replace(
          replace(
          replace(
          replace(
          replace(
          replace(
          replace(
          replace(
          replace(
          replace(replace(replace(testPrefixPattern, '[', 'LB'),']', 'RB'),'{', 'LC'),'}', 'RC'),',', 'COMMA'),'-', 'DASH'),
          '*', 'STAR'),
          '?', 'QMARK'),
          '\', 'BS'),
          '.', 'DOT'),
          '(', 'LP'),
          ')', 'RP'),
          '=', 'EQUALS') }}

        timeoutInMinutes: 120
        displayName: 'E2E Tests - Web ${{parameters.versionBranch}} - Via ${{parameters.teamsJsReferenceType}} - ${{parameters.hostingEnvironmentType}} Hosted - ${{testPrefixPattern}}'
        pool:
          name: Azure-Pipelines-1ESPT-ExDShared
          image: 'ubuntu-latest'
          os: linux
        variables:
          - name: envType
            ${{ if eq(parameters.teamsJsReferenceType, 'npm') }}:
              value: 'test'
            ${{ else }}:
              value: 'localScriptTag'
        steps:
          - template: build-app-host.yml
            parameters:
              appHostGitPath: AppHostingSdk

          - task: CmdLine@2
            displayName: 'Build Local Test App to Reference via Script Tag'
            condition: and(succeeded(), eq('${{ parameters.teamsJsReferenceType }}', 'scriptTag'))
            inputs:
              script: |
                pnpm build-test-app-local
              workingDirectory: '$(ClientSdkProjectDirectory)'

          - script: |
              sudo apt-get install -y libnss3-tools
              curl -JLO "https://dl.filippo.io/mkcert/latest?for=linux/amd64"
              chmod +x mkcert-v*-linux-amd64
              sudo mv mkcert-v*-linux-amd64 /usr/local/bin/mkcert
            displayName: 'Install mkcert using pre-built binary'
            condition: and(succeeded(), ${{ eq(testPrefixPattern, '{[S],[s]}') }})

          - powershell: |
              pnpm setup-ssr-app-cert
            displayName: 'Setup SSR app certificates for SSR test app'
            workingDirectory: 'microsoft-teams-library-js'
            condition: and(succeeded(), ${{ eq(testPrefixPattern, '{[S],[s]}') }})

          - powershell: |
              pnpm --filter ssr-test-app build
            displayName: 'Build teamsjs SSR test app'
            workingDirectory: 'microsoft-teams-library-js'
            condition: and(succeeded(), ${{ eq(testPrefixPattern, '{[S],[s]}') }})

          - bash: >
              pnpm exec ts-node tools/cli/runAppsWithE2ETests.ts
              --useDataFromLocal=true
              --testPrefixPattern "${{testPrefixPattern}}"
              --envType=${{ variables.envType }}
              --ssr=${{ eq(testPrefixPattern, '{[S],[s]}') }}
            displayName: 'Run web hosted E2E integration tests (${{testPrefixPattern}})'
            condition: and(succeeded(), eq('${{ parameters.hostingEnvironmentType }}', 'standardWeb'))
            workingDirectory: '$(AppHostingSdkProjectDirectory)'

          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/e2e-tests-report*.xml'
              testRunTitle: 'E2E Tests - Default'
              mergeTestResults: true
            condition: succeededOrFailed()
