# This template handles running E2E tests (including all necessary setup steps) from the host SDK repo for various environments.
# It will run one E2E job for each testPrefixPattern selector in the testPrefixPatternGroups parameter.

parameters:
  - name: AppHostingSdk
    default: none
    type: string

jobs:
  - job: E2ETest1
    displayName: 'E2E Test - Perf'
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: 'ubuntu-latest'
      os: linux
    steps:
      - template: tools/yaml-templates/build-app-host.yml@self
        parameters:
          appHostGitPath: AppHostingSdk

      - task: Bash@3
        displayName: 'Run E2E Perf tests'
        condition: succeeded()
        inputs:
          targetType: inline
          script: 'pnpm exec ts-node tools/cli/runAppsWithE2ETests.ts --appUrl=https://localhost:4002 --reportFileName=e2e-tests-report-perf --envType=perf'
          workingDirectory: '$(AppHostingSdkProjectDirectory)'

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/e2e-tests-report*.xml'
          testRunTitle: 'E2E Tests - Perf'
          mergeTestResults: true
        condition: succeededOrFailed()

  - template: tools/yaml-templates/web-e2e-tests-job.yml@self
    parameters:
      AppHostingSdk: AppHostingSdk
      hostingEnvironmentType: 'standardWeb'
      teamsJsReferenceType: 'npm'
      testPrefixPatternGroups: ['{[0-9],[A-D],[a-d]}', '{[E],[e]}', '{[F-M],[f-m]}', '{[N-Z],[n-z]}']

  - template: tools/yaml-templates/web-e2e-tests-job.yml@self
    parameters:
      AppHostingSdk: AppHostingSdk
      hostingEnvironmentType: 'standardWeb'
      teamsJsReferenceType: 'scriptTag'
      testPrefixPatternGroups: ['{[0-9],[A-D],[a-d]}', '{[E],[e]}', '{[F-M],[f-m]}', '{[N-Z],[n-z]}']

  - template: tools/yaml-templates/web-e2e-tests-job.yml@self
    parameters:
      AppHostingSdk: AppHostingSdk
      hostingEnvironmentType: 'electron'
      teamsJsReferenceType: 'npm'

  - job: E2ETestCDN
    displayName: 'E2E Tests - CDN (only runs on release builds)'
    # This test only runs after deployment from a release branch and the new CDN version has been deployed
    # This check will run on the PR to merge the release branch back into main
    condition: and(
      eq(variables['Build.Reason'], 'PullRequest'),
      startsWith(variables['System.PullRequest.SourceBranch'], 'release/'),
      eq(variables['System.PullRequest.TargetBranch'], 'main')
      )
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: 'ubuntu-latest'
      os: linux
    steps:
      - template: tools/yaml-templates/build-app-host.yml@self
        parameters:
          appHostGitPath: AppHostingSdk

      - task: CmdLine@2
        displayName: 'Build Test App CDN'
        inputs:
          script: |
            pnpm build-test-app-CDN
          workingDirectory: '$(ClientSdkProjectDirectory)'

      - bash: 'pnpm exec ts-node tools/cli/runAppsWithE2ETests.ts --useDataFromLocal=true --reportFileName=e2e-tests-report-cdn-script-tag --envType=cdnScriptTag'
        displayName: 'Run E2E integration tests with local script tag on latest cdn bundles'
        condition: succeeded()
        workingDirectory: '$(AppHostingSdkProjectDirectory)'
        enabled: true

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/e2e-tests-report*.xml'
          testRunTitle: 'E2E Tests - CDN'
          mergeTestResults: true
        condition: succeededOrFailed()
