parameters:
  - name: AppHostingSdk
    default: none
    type: string
  - name: versionBranch
    default: 'Latest'
    type: string

jobs:
  - template: web-e2e-tests-job.yml@self
    parameters:
      AppHostingSdk: AppHostingSdk
      hostingEnvironmentType: 'standardWeb'
      teamsJsReferenceType: 'npm'
      testPrefixPatternGroups:
        [
          'app(?=\\.)',
          '{appE,appI,appS,auth}',
          '{[B],[b]}',
          '{[C-D],[c-d]}',
          '{[E],[e]}',
          '{[F-M],[f-m]}',
          '{[N-Z],[n-z]}',
        ]
      versionBranch: ${{parameters.versionBranch}}

  - template: web-e2e-tests-job.yml@self
    parameters:
      AppHostingSdk: AppHostingSdk
      hostingEnvironmentType: 'standardWeb'
      teamsJsReferenceType: 'scriptTag'
      testPrefixPatternGroups:
        [
          'app(?=\\.)',
          '{appE,appI,appS,auth}',
          '{[B],[b]}',
          '{[C-D],[c-d]}',
          '{[E],[e]}',
          '{[F-M],[f-m]}',
          '{[N-Z],[n-z]}',
        ]
      versionBranch: ${{parameters.versionBranch}}

  - template: web-e2e-tests-job.yml@self
    parameters:
      AppHostingSdk: AppHostingSdk
      hostingEnvironmentType: 'electron'
      teamsJsReferenceType: 'npm'
      versionBranch: ${{parameters.versionBranch}}
