variables:
  - group: InfoSec-SecurityResults
  - name: products
    value: 6eff390d-80c0-4456-81b6-6abafa71e768

trigger:
  branches:
    include:
      - 'main'
      - 'release/*'

resources:
  repositories:
    - repository: GovernedTemplates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/Microsoft.Official.yml@GovernedTemplates
  parameters:
    platform:
      name: m365
      workload: Substrate
      serviceTreeId: $(serviceTreeId)
      serviceGroupName: Platform
    stages:
      - stage: __default
        jobs:
          - job: Security
            displayName: 'Security Tasks'
            steps:
              - template: tools/yaml-templates/security.yml@self

          - job: Build
            displayName: 'Build Test Publish'
            steps:
              - template: tools/yaml-templates/build-test-publish.yml@self

            templateContext:
              outputs:
                - output: pipelineArtifact
                  displayName: 'Publish bundle analysis'
                  condition: and( in(variables['Agent.JobStatus'], 'Succeeded', 'SucceededWithIssues'), eq(variables['Build.Reason'], 'PullRequest'), eq(variables['System.PullRequest.TargetBranch'], 'main'))
                  targetPath: './common/temp/bundleAnalysis'
                  artifactName: '$(bundleArtifactName)'

                - output: pipelineArtifact
                  displayName: 'Publish Test app artifacts'
                  targetPath: '$(Build.ArtifactStagingDirectory)\teams-test-app\$(Build.BuildId).zip'
                  artifactName: 'teams-test-app'
                  sbomBuildDropPath: '$(Build.ArtifactStagingDirectory)\teams-test-app'
                  sbomPackageName: 'teamstestappArtifact'

                - output: pipelineArtifact
                  displayName: 'Publish CDN feed to build Artifacts'
                  targetPath: '$(Build.ArtifactStagingDirectory)\CDNFeed'
                  artifactName: 'CDNFeed'

                - output: pipelineArtifact
                  displayName: 'Publish validDomains to Build Artifacts'
                  targetPath: '$(Build.ArtifactStagingDirectory)\validDomains'
                  artifactName: 'validDomains'

                - output: pipelineArtifact
                  displayName: 'Publish NPM feed to Build Artifacts'
                  targetPath: '$(Build.ArtifactStagingDirectory)\NPMFeed'
                  artifactName: 'NPMFeed'

                - output: pipelineArtifact
                  displayName: 'Publish Powershell Scripts to Build Artifacts'
                  targetPath: '$(Build.ArtifactStagingDirectory)\scripts'
                  artifactName: 'scripts'
