trigger: none
resources:
  repositories:
    - repository: GovernedTemplates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main
  pipelines:
    - pipeline: microsoft-teams-library-js-pipeline
      source: 'microsoft-teams-library-js/M365 Platform/App SDK/OfficeDev.microsoft-teams-library-js'
      project: ISS
extends:
  template: v2/Microsoft.Official.yml@GovernedTemplates
  parameters:
    platform:
      name: m365
      workload: Substrate
      serviceTreeId: $(serviceTreeId)
      serviceGroupName: Platform
    stages:
      - stage: Prod_Lockbox_Approval_Deployment
        displayName: Lockbox Approval/Deployment
        dependsOn: []
        variables:
          stage_type: deployment
          azure_subscription_ids: $(subscriptionId)
        jobs:
          - job: Agent_job
            condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))
            pool:
              type: release
            steps:
              - download: microsoft-teams-library-js-pipeline
              - task: prepare-deployment@1
                displayName:
                inputs:
                  taskType: credentialFetchTaskAzureRM
                  armserviceconnection: $(serviceConnectionId)
                  subscriptionid: $(subscriptionId)
              - task: AzureKeyVault@2
                displayName: 'Azure Key Vault: $(keyVaultName)'
                inputs:
                  ConnectedServiceName: $(serviceConnectionId)
                  KeyVaultName: $(keyVaultName)
                  SecretsFilter: $(keyVaultSecretsFilter)
              - task: NodeTool@0
                displayName: Use Node 18.x
                inputs:
                  versionSpec: 18.x
              - task: PowerShell@2
                displayName: Update npmrc with NPM-TOKEN
                inputs:
                  targetType: 'inline'
                  script: Set-Content -Path $(PIPELINE.WORKSPACE)/microsoft-teams-library-js-pipeline/NPMFeed/.npmrc -Value "//registry.npmjs.org/:_authToken=$(NPM-TOKEN)"
              - task: Npm@1
                displayName: Publish to npm (tag latest) KV
                inputs:
                  command: custom
                  workingDir: $(PIPELINE.WORKSPACE)/microsoft-teams-library-js-pipeline/NPMFeed
                  verbose: false
                  customCommand: publish --tag latest
              - task: M365CdnAssetsUpload@1
                displayName: Push teams-js to M365 1CDN (Prod)
                inputs:
                  SourcePath: $(PIPELINE.WORKSPACE)/microsoft-teams-library-js-pipeline/CDNFeed/*
                  ConnectedServiceNameARM: $(serviceConnectionId)
                  ContainerName: teams-js
                  AdditionalArgumentsForBlobCopy: --overwrite=false --log-level=INFO --recursive
              - task: AssetRetention@3
                displayName: ARtifact Retention Orchestrator Workflow (ARROW)
                inputs:
                  ArrowServiceConnection: $(arrowServiceConnectionId)
                  IsShipped: true
