trigger: none
resources:
  repositories:
    - repository: CustomPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/OfficePipelineTemplates
      ref: refs/tags/release
  pipelines:
    - pipeline: microsoft-teams-library-js-pipeline
      source: 'microsoft-teams-library-js/M365 Platform/App SDK/OfficeDev.microsoft-teams-library-js'
      project: ISS
variables:
  - name: System.Debug
    value: true
extends:
  template: v1/Office.Official.PipelineTemplate.yml@CustomPipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: windows-latest
      os: windows
    serviceTreeId: $(serviceTreeId)
    customBuildTags:
      - ES365AIMigrationTooling-Release-MOBR
    stages:
      - stage: Prod_Lockbox_Approval_Deployment
        displayName: Lockbox Approval/Deployment
        dependsOn: []
        templateContext:
          cloud: Public
          isProduction: false
          approval:
            workflow: lockbox
            scope:
              serviceGroupName: Platform
              subscriptionIds:
                - $(subscriptionId)
        jobs:
          - job: Agent_job
            templateContext:
              type: releaseJob
              workflow: m365-custom
              inputs:
                - input: pipelineArtifact
                  pipeline: microsoft-teams-library-js-pipeline
                  artifactName: NPMFeed
                  targetPath: $(System.DefaultWorkingDirectory)/microsoft-teams-library-js-pipeline/NPMFeed
                - input: pipelineArtifact
                  pipeline: microsoft-teams-library-js-pipeline
                  artifactName: CDNFeed
                  targetPath: $(System.DefaultWorkingDirectory)/microsoft-teams-library-js-pipeline/CDNFeed

            steps:
              - task: prepare-deployment@1
                displayName:
                inputs:
                  taskType: credentialFetchTaskAzureRM
                  armserviceconnection: $(serviceConnectionId)
                  subscriptionid: $(subscriptionId)
              - task: AssetRetention@3
                displayName: ARtifact Retention Orchestrator Workflow (ARROW)
                inputs:
                  ArrowServiceConnection: $(arrowServiceConnectionId)
                  IsShipped: true
              - task: NodeTool@0
                displayName: Use Node 18.x
                inputs:
                  versionSpec: 18.x
              - task: Npm@1
                displayName: Build NPM package for release
                inputs:
                  command: custom
                  workingDir: $(System.DefaultWorkingDirectory)/microsoft-teams-library-js-pipeline/NPMFeed
                  verbose: false
                  customCommand: pack
              - task: EsrpRelease@10
                displayName: Publish to npm (tag beta) - ESRP release
                inputs:
                  connectedservicename: '$(connectedServiceName)'
                  usemanagedidentity: true
                  keyvaultname: '$(keyVaultName)'
                  signcertname: '$(signCertName)'
                  clientid: '$(clientId)'
                  intent: 'PackageDistribution'
                  contenttype: 'npm'
                  contentsource: 'Folder'
                  folderlocation: '$(System.DefaultWorkingDirectory)/microsoft-teams-library-js-pipeline/NPMFeed'
                  waitforreleasecompletion: true
                  owners: $(owners)
                  approvers: $(approvers)
                  serviceendpointurl: '$(serviceEndpointUrl)'
                  mainpublisher: '$(mainPublisher)'
                  domaintenantid: '$(domainTenantId)'
                  productstate: 'Beta'
              - task: M365CdnAssetsUpload@3
                displayName: Push teams-js to M365 1CDN (SDF)
                inputs:
                  SourcePath: $(System.DefaultWorkingDirectory)/microsoft-teams-library-js-pipeline/CDNFeed/*
                  ConnectedServiceNameARM: $(serviceConnectionId)
                  Environment: PublicCloudSDF
                  ContainerName: teams-js
                  AdditionalArgumentsForBlobCopy: --overwrite=false --log-level=INFO --recursive
              - task: PowerShell@2
                displayName: View Published Package URLs
                inputs:
                  targetType: 'filePath'
                  filePath: 'tools/releases/powershell-commands/view-published-pkg-urls.ps1'
                  arguments: -PIPELINE_WORKSPACE $(System.DefaultWorkingDirectory)
