/** country code. */
export enum Country {
  /** Afghanistan */
  AF = 'AF',
  /** AlandIslands */
  AX = 'AX',
  /** Albania */
  AL = 'AL',
  /** Algeria */
  DZ = 'DZ',
  /** AmericanSamoa */
  AS = 'AS',
  /** Andorra */
  AD = 'AD',
  /** Angola */
  AO = 'AO',
  /** Anguilla */
  AI = 'AI',
  /** Antarctica */
  AQ = 'AQ',
  /** AntiguaAndBarbuda */
  AG = 'AG',
  /** Argentina */
  AR = 'AR',
  /** Armenia */
  AM = 'AM',
  /** Aruba */
  AW = 'AW',
  /** Australia */
  AU = 'AU',
  /** Austria */
  AT = 'AT',
  /** Azerbaijan */
  AZ = 'AZ',
  /** Bahamas */
  BS = 'BS',
  /** Bahrain */
  BH = 'BH',
  /** Bangladesh */
  BD = 'BD',
  /** Barbados */
  BB = 'BB',
  /** Belarus */
  BY = 'BY',
  /** Belgium */
  BE = 'BE',
  /** Belize */
  BZ = 'BZ',
  /** Benin */
  BJ = 'BJ',
  /** Bermuda */
  BM = 'BM',
  /** Bhutan */
  BT = 'BT',
  /** Bolivia */
  BO = 'BO',
  /** BonaireSintEustatiusSaba */
  BQ = 'BQ',
  /** BosniaAndHerzegovina */
  BA = 'BA',
  /** Botswana */
  BW = 'BW',
  /** BouvetIsland */
  BV = 'BV',
  /** Brazil */
  BR = 'BR',
  /** BritishIndianOceanTerritory */
  IO = 'IO',
  /** BruneiDarussalam */
  BN = 'BN',
  /** Bulgaria */
  BG = 'BG',
  /** BurkinaFaso */
  BF = 'BF',
  /** Burundi */
  BI = 'BI',
  /** Cambodia */
  KH = 'KH',
  /** Cameroon */
  CM = 'CM',
  /** Canada */
  CA = 'CA',
  /** CapeVerde */
  CV = 'CV',
  /** CaymanIslands */
  KY = 'KY',
  /** CentralAfricanRepublic */
  CF = 'CF',
  /** Chad */
  TD = 'TD',
  /** Chile */
  CL = 'CL',
  /** China */
  CN = 'CN',
  /** ChristmasIsland */
  CX = 'CX',
  /** CocosKeelingIslands */
  CC = 'CC',
  /** Colombia */
  CO = 'CO',
  /** Comoros */
  KM = 'KM',
  /** Congo */
  CG = 'CG',
  /** CongoDemocraticRepublic */
  CD = 'CD',
  /** CookIslands */
  CK = 'CK',
  /** CostaRica */
  CR = 'CR',
  /** CoteDIvoire */
  CI = 'CI',
  /** Croatia */
  HR = 'HR',
  /** Cuba */
  CU = 'CU',
  /** Curaçao */
  CW = 'CW',
  /** Cyprus */
  CY = 'CY',
  /** CzechRepublic */
  CZ = 'CZ',
  /** Denmark */
  DK = 'DK',
  /** Djibouti */
  DJ = 'DJ',
  /** Dominica */
  DM = 'DM',
  /** DominicanRepublic */
  DO = 'DO',
  /** Ecuador */
  EC = 'EC',
  /** Egypt */
  EG = 'EG',
  /** ElSalvador */
  SV = 'SV',
  /** EquatorialGuinea */
  GQ = 'GQ',
  /** Eritrea */
  ER = 'ER',
  /** Estonia */
  EE = 'EE',
  /** Ethiopia */
  ET = 'ET',
  /** FalklandIslands */
  FK = 'FK',
  /** FaroeIslands */
  FO = 'FO',
  /** Fiji */
  FJ = 'FJ',
  /** Finland */
  FI = 'FI',
  /** France */
  FR = 'FR',
  /** FrenchGuiana */
  GF = 'GF',
  /** FrenchPolynesia */
  PF = 'PF',
  /** FrenchSouthernTerritories */
  TF = 'TF',
  /** Gabon */
  GA = 'GA',
  /** Gambia */
  GM = 'GM',
  /** Georgia */
  GE = 'GE',
  /** Germany */
  DE = 'DE',
  /** Ghana */
  GH = 'GH',
  /** Gibraltar */
  GI = 'GI',
  /** Greece */
  GR = 'GR',
  /** Greenland */
  GL = 'GL',
  /** Grenada */
  GD = 'GD',
  /** Guadeloupe */
  GP = 'GP',
  /** Guam */
  GU = 'GU',
  /** Guatemala */
  GT = 'GT',
  /** Guernsey */
  GG = 'GG',
  /** Guinea */
  GN = 'GN',
  /** GuineaBissau */
  GW = 'GW',
  /** Guyana */
  GY = 'GY',
  /** Haiti */
  HT = 'HT',
  /** HeardIslandMcdonaldIslands */
  HM = 'HM',
  /** HolySeeVaticanCityState */
  VA = 'VA',
  /** Honduras */
  HN = 'HN',
  /** HongKong */
  HK = 'HK',
  /** Hungary */
  HU = 'HU',
  /** Iceland */
  IS = 'IS',
  /** India */
  IN = 'IN',
  /** Indonesia */
  ID = 'ID',
  /** Iran */
  IR = 'IR',
  /** Iraq */
  IQ = 'IQ',
  /** Ireland */
  IE = 'IE',
  /** IsleOfMan */
  IM = 'IM',
  /** Israel */
  IL = 'IL',
  /** Italy */
  IT = 'IT',
  /** Jamaica */
  JM = 'JM',
  /** Japan */
  JP = 'JP',
  /** Jersey */
  JE = 'JE',
  /** Jordan */
  JO = 'JO',
  /** Kazakhstan */
  KZ = 'KZ',
  /** Kenya */
  KE = 'KE',
  /** Kiribati */
  KI = 'KI',
  /** Korea */
  KR = 'KR',
  /** KoreaDemocraticPeoplesRepublic */
  KP = 'KP',
  /** Kuwait */
  KW = 'KW',
  /** Kyrgyzstan */
  KG = 'KG',
  /** LaoPeoplesDemocraticRepublic */
  LA = 'LA',
  /** Latvia */
  LV = 'LV',
  /** Lebanon */
  LB = 'LB',
  /** Lesotho */
  LS = 'LS',
  /** Liberia */
  LR = 'LR',
  /** LibyanArabJamahiriya */
  LY = 'LY',
  /** Liechtenstein */
  LI = 'LI',
  /** Lithuania */
  LT = 'LT',
  /** Luxembourg */
  LU = 'LU',
  /** Macao */
  MO = 'MO',
  /** Macedonia */
  MK = 'MK',
  /** Madagascar */
  MG = 'MG',
  /** Malawi */
  MW = 'MW',
  /** Malaysia */
  MY = 'MY',
  /** Maldives */
  MV = 'MV',
  /** Mali */
  ML = 'ML',
  /** Malta */
  MT = 'MT',
  /** MarshallIslands */
  MH = 'MH',
  /** Martinique */
  MQ = 'MQ',
  /** Mauritania */
  MR = 'MR',
  /** Mauritius */
  MU = 'MU',
  /** Mayotte */
  YT = 'YT',
  /** Mexico */
  MX = 'MX',
  /** Micronesia */
  FM = 'FM',
  /** Moldova */
  MD = 'MD',
  /** Monaco */
  MC = 'MC',
  /** Mongolia */
  MN = 'MN',
  /** Montenegro */
  ME = 'ME',
  /** Montserrat */
  MS = 'MS',
  /** Morocco */
  MA = 'MA',
  /** Mozambique */
  MZ = 'MZ',
  /** Myanmar */
  MM = 'MM',
  /** Namibia */
  NA = 'NA',
  /** Nauru */
  NR = 'NR',
  /** Nepal */
  NP = 'NP',
  /** Netherlands */
  NL = 'NL',
  /** NewCaledonia */
  NC = 'NC',
  /** NewZealand */
  NZ = 'NZ',
  /** Nicaragua */
  NI = 'NI',
  /** Niger */
  NE = 'NE',
  /** Nigeria */
  NG = 'NG',
  /** Niue */
  NU = 'NU',
  /** NorfolkIsland */
  NF = 'NF',
  /** NorthernMarianaIslands */
  MP = 'MP',
  /** Norway */
  NO = 'NO',
  /** Oman */
  OM = 'OM',
  /** Pakistan */
  PK = 'PK',
  /** Palau */
  PW = 'PW',
  /** PalestinianTerritory */
  PS = 'PS',
  /** Panama */
  PA = 'PA',
  /** PapuaNewGuinea */
  PG = 'PG',
  /** Paraguay */
  PY = 'PY',
  /** Peru */
  PE = 'PE',
  /** Philippines */
  PH = 'PH',
  /** Pitcairn */
  PN = 'PN',
  /** Poland */
  PL = 'PL',
  /** Portugal */
  PT = 'PT',
  /** PuertoRico */
  PR = 'PR',
  /** Qatar */
  QA = 'QA',
  /** Reunion */
  RE = 'RE',
  /** Romania */
  RO = 'RO',
  /** RussianFederation */
  RU = 'RU',
  /** Rwanda */
  RW = 'RW',
  /** SaintBarthelemy */
  BL = 'BL',
  /** SaintHelena */
  SH = 'SH',
  /** SaintKittsAndNevis */
  KN = 'KN',
  /** SaintLucia */
  LC = 'LC',
  /** SaintMartin */
  MF = 'MF',
  /** SaintPierreAndMiquelon */
  PM = 'PM',
  /** SaintVincentAndGrenadines */
  VC = 'VC',
  /** Samoa */
  WS = 'WS',
  /** SanMarino */
  SM = 'SM',
  /** SaoTomeAndPrincipe */
  ST = 'ST',
  /** SaudiArabia */
  SA = 'SA',
  /** Senegal */
  SN = 'SN',
  /** Serbia */
  RS = 'RS',
  /** Seychelles */
  SC = 'SC',
  /** SierraLeone */
  SL = 'SL',
  /** Singapore */
  SG = 'SG',
  /** SintMaarten */
  SX = 'SX',
  /** Slovakia */
  SK = 'SK',
  /** Slovenia */
  SI = 'SI',
  /** SolomonIslands */
  SB = 'SB',
  /** Somalia */
  SO = 'SO',
  /** SouthAfrica */
  ZA = 'ZA',
  /** SouthGeorgiaAndSandwichIsl */
  GS = 'GS',
  /** SouthSudan */
  SS = 'SS',
  /** Spain */
  ES = 'ES',
  /** SriLanka */
  LK = 'LK',
  /** Sudan */
  SD = 'SD',
  /** Suriname */
  SR = 'SR',
  /** SvalbardAndJanMayen */
  SJ = 'SJ',
  /** Swaziland */
  SZ = 'SZ',
  /** Sweden */
  SE = 'SE',
  /** Switzerland */
  CH = 'CH',
  /** SyrianArabRepublic */
  SY = 'SY',
  /** Taiwan */
  TW = 'TW',
  /** Tajikistan */
  TJ = 'TJ',
  /** Tanzania */
  TZ = 'TZ',
  /** Thailand */
  TH = 'TH',
  /** TimorLeste */
  TL = 'TL',
  /** Togo */
  TG = 'TG',
  /** Tokelau */
  TK = 'TK',
  /** Tonga */
  TO = 'TO',
  /** TrinidadAndTobago */
  TT = 'TT',
  /** Tunisia */
  TN = 'TN',
  /** Turkey */
  TR = 'TR',
  /** Turkmenistan */
  TM = 'TM',
  /** TurksAndCaicosIslands */
  TC = 'TC',
  /** Tuvalu */
  TV = 'TV',
  /** Uganda */
  UG = 'UG',
  /** Ukraine */
  UA = 'UA',
  /** UnitedArabEmirates */
  AE = 'AE',
  /** UnitedKingdom */
  GB = 'GB',
  /** UnitedStates */
  US = 'US',
  /** UnitedStatesOutlyingIslands */
  UM = 'UM',
  /** Uruguay */
  UY = 'UY',
  /** Uzbekistan */
  UZ = 'UZ',
  /** Vanuatu */
  VU = 'VU',
  /** Venezuela */
  VE = 'VE',
  /** Vietnam */
  VN = 'VN',
  /** VirginIslandsBritish */
  VG = 'VG',
  /** VirginIslandsUS */
  VI = 'VI',
  /** WallisAndFutuna */
  WF = 'WF',
  /** WesternSahara */
  EH = 'EH',
  /** Yemen */
  YE = 'YE',
  /** Zambia */
  ZM = 'ZM',
  /** Zimbabwe */
  ZW = 'ZW',
}
