import { build } from '../replacementsGenerator';

/**
 * constant package name defined here
 */
const sourcePackage = 'microsoftTeams';
const targetPackage = 'teamsjs';

test('build replacements through mappings.json', () => {
  expect(build()).toEqual([
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: [],
      targetPrefixTokens: ['core'],
      sourceMethod: 'initialize',
      targetMethod: 'initialize',
      sourceTokens: ['microsoftTeams', 'initialize'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: [],
      targetPrefixTokens: ['core'],
      sourceMethod: 'getContext',
      targetMethod: 'getContext',
      sourceTokens: ['microsoftTeams', 'getContext'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: [],
      targetPrefixTokens: ['core'],
      sourceMethod: 'shareDeepLink',
      targetMethod: 'shareDeepLink',
      sourceTokens: ['microsoftTeams', 'shareDeepLink'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: [],
      targetPrefixTokens: ['core'],
      sourceMethod: 'executeDeepLink',
      targetMethod: 'executeDeepLink',
      sourceTokens: ['microsoftTeams', 'executeDeepLink'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: [],
      targetPrefixTokens: ['core'],
      sourceMethod: 'registerOnThemeChangeHandler',
      targetMethod: 'registerOnThemeChangeHandler',
      sourceTokens: ['microsoftTeams', 'registerOnThemeChangeHandler'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: ['authentication'],
      targetPrefixTokens: ['authentication'],
      sourceMethod: 'authenticate',
      targetMethod: 'authenticate',
      sourceTokens: ['microsoftTeams', 'authentication', 'authenticate'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: ['authentication'],
      targetPrefixTokens: ['authentication'],
      sourceMethod: 'getAuthToken',
      targetMethod: 'getAuthToken',
      sourceTokens: ['microsoftTeams', 'authentication', 'getAuthToken'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: ['authentication'],
      targetPrefixTokens: ['authentication'],
      sourceMethod: 'notifyFailure',
      targetMethod: 'notifyFailure',
      sourceTokens: ['microsoftTeams', 'authentication', 'notifyFailure'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: ['authentication'],
      targetPrefixTokens: ['authentication'],
      sourceMethod: 'notifySuccess',
      targetMethod: 'notifySuccess',
      sourceTokens: ['microsoftTeams', 'authentication', 'notifySuccess'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: ['authentication'],
      targetPrefixTokens: ['authentication'],
      sourceMethod: 'initialize',
      targetMethod: 'initialize',
      sourceTokens: ['microsoftTeams', 'authentication', 'initialize'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: ['settings'],
      targetPrefixTokens: ['pages', 'config'],
      sourceMethod: 'getSettings',
      targetMethod: 'getConfig',
      sourceTokens: ['microsoftTeams', 'settings', 'getSettings'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: ['settings'],
      targetPrefixTokens: ['pages', 'config'],
      sourceMethod: 'setSettings',
      targetMethod: 'setConfig',
      sourceTokens: ['microsoftTeams', 'settings', 'setSettings'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: ['settings'],
      targetPrefixTokens: ['pages', 'config'],
      sourceMethod: 'setValidityState',
      targetMethod: 'setValidityState',
      sourceTokens: ['microsoftTeams', 'settings', 'setValidityState'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: ['settings'],
      targetPrefixTokens: ['pages', 'config'],
      sourceMethod: 'registerOnSaveHandler',
      targetMethod: 'registerOnSaveHandler',
      sourceTokens: ['microsoftTeams', 'settings', 'registerOnSaveHandler'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: ['settings'],
      targetPrefixTokens: ['pages', 'config'],
      sourceMethod: 'registerOnRemoveHandler',
      targetMethod: 'registerOnRemoveHandler',
      sourceTokens: ['microsoftTeams', 'settings', 'registerOnRemoveHandler'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: ['settings'],
      targetPrefixTokens: ['pages', 'config'],
      sourceMethod: 'initialize',
      targetMethod: 'initialize',
      sourceTokens: ['microsoftTeams', 'settings', 'initialize'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: ['tasks'],
      targetPrefixTokens: ['dialog'],
      sourceMethod: 'startTask',
      targetMethod: 'open',
      sourceTokens: ['microsoftTeams', 'tasks', 'startTask'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: ['tasks'],
      targetPrefixTokens: ['dialog'],
      sourceMethod: 'submitTask',
      targetMethod: 'submit',
      sourceTokens: ['microsoftTeams', 'tasks', 'submitTask'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: ['tasks'],
      targetPrefixTokens: ['dialog'],
      sourceMethod: 'updateTask',
      targetMethod: 'resize',
      sourceTokens: ['microsoftTeams', 'tasks', 'updateTask'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: ['appInitialization'],
      targetPrefixTokens: ['appInitialization'],
      sourceMethod: 'notifyAppLoaded',
      targetMethod: 'notifyAppLoaded',
      sourceTokens: ['microsoftTeams', 'appInitialization', 'notifyAppLoaded'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: ['appInitialization'],
      targetPrefixTokens: ['appInitialization'],
      sourceMethod: 'notifyExpectedFailure',
      targetMethod: 'notifyExpectedFailure',
      sourceTokens: ['microsoftTeams', 'appInitialization', 'notifyExpectedFailure'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: ['appInitialization'],
      targetPrefixTokens: ['appInitialization'],
      sourceMethod: 'notifyFailure',
      targetMethod: 'notifyFailure',
      sourceTokens: ['microsoftTeams', 'appInitialization', 'notifyFailure'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: ['appInitialization'],
      targetPrefixTokens: ['appInitialization'],
      sourceMethod: 'notifySuccess',
      targetMethod: 'notifySuccess',
      sourceTokens: ['microsoftTeams', 'appInitialization', 'notifySuccess'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: ['location'],
      targetPrefixTokens: ['location'],
      sourceMethod: 'getLocation',
      targetMethod: 'getLocation',
      sourceTokens: ['microsoftTeams', 'location', 'getLocation'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: ['location'],
      targetPrefixTokens: ['location'],
      sourceMethod: 'showLocation',
      targetMethod: 'showLocation',
      sourceTokens: ['microsoftTeams', 'location', 'showLocation'],
    },
  ]);
});
