import { build } from '../replacementsGenerator';

/**
 * constant package name defined here
 */
const sourcePackage = 'microsoftTeams';
const targetPackage = 'teamsjs';

test('build replacements through mappings.json', () => {
  expect(build()).toEqual([
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: [],
      targetPrefixTokens: ['core'],
      sourceMethod: 'initialize',
      targetMethod: 'initialize',
      sourceTokens: ['microsoftTeams', 'initialize'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: [],
      targetPrefixTokens: ['core'],
      sourceMethod: 'getContext',
      targetMethod: 'getContext',
      sourceTokens: ['microsoftTeams', 'getContext'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: [],
      targetPrefixTokens: ['core'],
      sourceMethod: 'shareDeepLink',
      targetMethod: 'shareDeepLink',
      sourceTokens: ['microsoftTeams', 'shareDeepLink'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: [],
      targetPrefixTokens: ['core'],
      sourceMethod: 'executeDeepLink',
      targetMethod: 'executeDeepLink',
      sourceTokens: ['microsoftTeams', 'executeDeepLink'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: [],
      targetPrefixTokens: ['core'],
      sourceMethod: 'registerOnThemeChangeHandler',
      targetMethod: 'registerOnThemeChangeHandler',
      sourceTokens: ['microsoftTeams', 'registerOnThemeChangeHandler'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: ['authentication'],
      targetPrefixTokens: ['authentication'],
      sourceMethod: 'authenticate',
      targetMethod: 'authenticate',
      sourceTokens: ['microsoftTeams', 'authentication', 'authenticate'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: ['authentication'],
      targetPrefixTokens: ['authentication'],
      sourceMethod: 'getAuthToken',
      targetMethod: 'getAuthToken',
      sourceTokens: ['microsoftTeams', 'authentication', 'getAuthToken'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: ['authentication'],
      targetPrefixTokens: ['authentication'],
      sourceMethod: 'notifyFailure',
      targetMethod: 'notifyFailure',
      sourceTokens: ['microsoftTeams', 'authentication', 'notifyFailure'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: ['authentication'],
      targetPrefixTokens: ['authentication'],
      sourceMethod: 'notifySuccess',
      targetMethod: 'notifySuccess',
      sourceTokens: ['microsoftTeams', 'authentication', 'notifySuccess'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: ['authentication'],
      targetPrefixTokens: ['authentication'],
      sourceMethod: 'registerAuthenticationHandlers',
      targetMethod: 'registerAuthenticationHandlers',
      sourceTokens: ['microsoftTeams', 'authentication', 'registerAuthenticationHandlers'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: ['settings'],
      targetPrefixTokens: ['pages', 'config'],
      sourceMethod: 'getSettings',
      targetMethod: 'getConfig',
      sourceTokens: ['microsoftTeams', 'settings', 'getSettings'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: ['settings'],
      targetPrefixTokens: ['pages', 'config'],
      sourceMethod: 'setSettings',
      targetMethod: 'setConfig',
      sourceTokens: ['microsoftTeams', 'settings', 'setSettings'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: ['settings'],
      targetPrefixTokens: ['pages', 'config'],
      sourceMethod: 'setValidityState',
      targetMethod: 'setValidityState',
      sourceTokens: ['microsoftTeams', 'settings', 'setValidityState'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: ['settings'],
      targetPrefixTokens: ['pages', 'config'],
      sourceMethod: 'registerOnSaveHandler',
      targetMethod: 'registerOnSaveHandler',
      sourceTokens: ['microsoftTeams', 'settings', 'registerOnSaveHandler'],
    },
    {
      sourcePackage: sourcePackage,
      targetPackage: targetPackage,
      sourcePrefixTokens: ['settings'],
      targetPrefixTokens: ['pages', 'config'],
      sourceMethod: 'registerOnRemoveHandler',
      targetMethod: 'registerOnRemoveHandler',
      sourceTokens: ['microsoftTeams', 'settings', 'registerOnRemoveHandler'],
    },
  ]);
});
