# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/protobuf/internal/no_package.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)google/protobuf/internal/no_package.proto\";\n\x10NoPackageMessage\x12\'\n\x0fno_package_enum\x18\x01 \x01(\x0e\x32\x0e.NoPackageEnum*?\n\rNoPackageEnum\x12\x16\n\x12NO_PACKAGE_VALUE_0\x10\x00\x12\x16\n\x12NO_PACKAGE_VALUE_1\x10\x01')

_NOPACKAGEENUM = DESCRIPTOR.enum_types_by_name['NoPackageEnum']
NoPackageEnum = enum_type_wrapper.EnumTypeWrapper(_NOPACKAGEENUM)
NO_PACKAGE_VALUE_0 = 0
NO_PACKAGE_VALUE_1 = 1


_NOPACKAGEMESSAGE = DESCRIPTOR.message_types_by_name['NoPackageMessage']
NoPackageMessage = _reflection.GeneratedProtocolMessageType('NoPackageMessage', (_message.Message,), {
  'DESCRIPTOR' : _NOPACKAGEMESSAGE,
  '__module__' : 'google.protobuf.internal.no_package_pb2'
  # @@protoc_insertion_point(class_scope:NoPackageMessage)
  })
_sym_db.RegisterMessage(NoPackageMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NOPACKAGEENUM._serialized_start=106
  _NOPACKAGEENUM._serialized_end=169
  _NOPACKAGEMESSAGE._serialized_start=45
  _NOPACKAGEMESSAGE._serialized_end=104
# @@protoc_insertion_point(module_scope)
