name: Check for runtime version changes
on:
  pull_request:
    branches: [main]

jobs:
  Get-Changed-Files:
    runs-on: ubuntu-latest
    outputs:
      runtime_changed: ${{ steps.detect-runtime-change.outputs.runtime_changed }}
    steps:
      - uses: jitterbit/get-changed-files@v1
        id: changed_files
      - name: Check if runtime.ts has been modified
        id: detect_runtime_change
        run: |
          runtime_changed=false
          for changed_file in ${{ steps.changed_files.outputs.all }}; do
            if [ "$changed_file" = "packages/teams-js/src/public/runtime.ts" ]; then
              runtime_changed=true
            fi
          done
          echo "runtime_changed=$runtime_changed" >> $GITHUB_OUTPUT

  Comment-On-PR:
    runs-on: ubuntu-latest
    needs: Get-Changed-Files
    if: ${{needs.Get-Changed-Files.outputs.runtime_changed}} == true
    steps:
      - uses: actions/checkout@v2
      - name: Comment on PR
        uses: mb2dev/github-action-comment-pull-request@1.0.0
        with:
          message: "This pull request contains changes to the runtime.ts file. If you, as the author of this PR, have made changes to the Runtime interface please review RUNTIME.md to determine if a new runtime version is required. Please reply to this comment stating what changes, if any, were made to the runtime object and whether a new runtime version was required."
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


